// GENERATED by scripts/build-lastmod.mjs. Do not edit by hand.
//
// Per-route modification dates for the sitemap, derived from git (falling back
// to file mtime, then to the build date). Regenerated at prebuild. This file is
// committed so `npm run dev` and a fresh clone both have dates before any build
// has run.
//
// It exists as generated DATA, not as a lookup, so the sitemap routes can import
// it without pulling filesystem access into the Next build graph -- see the
// header of scripts/build-lastmod.mjs for what that cost the first time.

export const BUILD_DATE = "2026-07-28";

export const ROUTE_DATES: Record<string, string> = {
  "/": "2026-07-28",
  "/about/": "2026-07-28",
  "/advertising-on-chatgpt/": "2026-07-25",
  "/ai-search-visibility/": "2026-07-26",
  "/ai-visibility-audit/": "2026-07-25",
  "/are-we-a-good-fit/": "2026-07-28",
  "/build-your-vision/": "2026-07-23",
  "/contact/": "2026-07-28",
  "/custom-coded-static/": "2026-07-28",
  "/digital-marketing/": "2026-07-26",
  "/ecommerce/": "2026-07-23",
  "/email-marketing/": "2026-07-23",
  "/essays/": "2026-07-24",
  "/essays/chad-lewine-worlds-combine/": "2026-07-27",
  "/essays/is-your-agency-ripping-you-off/": "2026-07-27",
  "/essays/rebirth-of-chadworks-wondrous-internet/": "2026-07-27",
  "/faqs/": "2026-07-24",
  "/how-much-does-a-website-cost/": "2026-07-26",
  "/industries-served/": "2026-07-28",
  "/music-industry-web-design/": "2026-07-23",
  "/privacy-policy/": "2026-07-24",
  "/rates/": "2026-07-28",
  "/seo/": "2026-07-25",
  "/shapecap/": "2026-07-20",
  "/shopify/": "2026-07-23",
  "/show-up-on-chatgpt/": "2026-07-26",
  "/showroom/": "2026-07-28",
  "/showroom/rising-compass/": "2026-07-28",
  "/switch/gmail-to-workspace/": "2026-07-23",
  "/switch/godaddy-to-static/": "2026-07-23",
  "/switch/leave-social-media/": "2026-07-06",
  "/switch/leave-social-media/content-engine/": "2026-07-06",
  "/switch/leave-social-media/explorer/": "2026-07-06",
  "/switch/leave-social-media/proliferator/": "2026-07-06",
  "/switch/leave-social-media/sfvv/": "2026-07-06",
  "/switch/leave-social-media/world-pass/": "2026-07-06",
  "/switch/leave-wordpress/": "2026-07-23",
  "/switch/squarespace-to-static/": "2026-07-23",
  "/switch/wix-to-static/": "2026-07-23",
  "/terms-of-service/": "2026-07-24",
  "/visibility/": "2026-07-25",
  "/vision-strategy-roadmap/": "2026-07-23",
  "/web-design-for-authors/": "2026-07-23",
  "/web-design-packages/": "2026-07-23",
  "/web-design/": "2026-07-24",
  "/web-development/": "2026-07-24",
  "/web-hosting/": "2026-07-11",
  "/website-design-cost-calculator/": "2026-07-28",
  "/website-design-for-bands-musicians/": "2026-07-23",
  "/website-design-for-foundation-repair/": "2026-07-24",
  "/website-design-for-septic-services/": "2026-07-25",
  "/website-design-for-tree-companies/": "2026-07-23",
  "/website-redesign/": "2026-07-23",
  "/websites/": "2026-07-24",
  "/wordpress/": "2026-07-23",
};
