// Route: /are-we-a-good-fit/ -- the qualification room (CWS-EXPANSION-PLAN-01,
// item D). The positioning filter made into a page: it names the buyer chadworks
// is built for (people with big, wild ideas doubling down on their digital
// presence as craft, and against social/AI sameness) and, just as deliberately,
// tells the wrong-fit visitor to walk before they reach the form.
//
// Titled as a question at Chad's direction (2026-07-16). The old "Who I Work With"
// is grammatically wrong -- the pronoun is the object of "with", so it wants
// "whom" -- and "whom" fights the plain register the rest of the site uses.
//
// The homepage, /about/ and the service pages keep the FitCapsule tease and link
// here. This page does NOT render that capsule: its H1 already asks the question,
// so the band would only repeat it. It renders the bare QualPanels in the hero
// instead, fed by the same exported FIT copy, so the lists exist once.
//
// Copy follows the chad-lewine-crystopa-forge voice profile (manifesto register:
// no hedging, the tools/taste separation, real dollar amounts) and the humanizing
// SOP. JSON-LD: WebPage + BreadcrumbList.

import type { Metadata } from "next";
import Link from "next/link";
import { SITE_URL } from "@/lib/service";
import { ORG_ID, ref } from "@/lib/jsonld";
import { isLaunched } from "@/lib/launch";
import { LaunchLink } from "@/components/LaunchLink";
import { PageComposer, MainContactCapsule } from "@/components/capsules";
import { QualPanels } from "@/components/capsules/QualificationCapsule";
import { FIT } from "@/components/capsules/FitCapsule";
import { SectionShell } from "@/components/capsules/SectionShell";
import { BASE, money } from "@/lib/package-builder";
import { HIGH, LOW } from "@/lib/pricing";

const ROUTE = "/are-we-a-good-fit/";
const PAGE_URL = `${SITE_URL}${ROUTE}`;
const TITLE = "Are We A Good Fit? | chadworks' Preferred Client Type";
const DESCRIPTION =
  "chadworks doesn't work with everyone. This page shares what chadworks looks for in a client partner.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: PAGE_URL },
  // Launch-driven, and REQUIRED: layout.tsx defaults every route to noindex, so
  // being in launch.ts alone would still serve noindex. Both edits or neither.
  robots: { index: isLaunched(ROUTE), follow: true },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: PAGE_URL,
    type: "website",
    images: [{ url: "/og-default.png", width: 1200, height: 630, alt: "chadworks" }],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/og-default.png"],
  },
};

const webPageJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Are We A Good Fit?",
  url: PAGE_URL,
  description: DESCRIPTION,
  about: ref(ORG_ID),
};

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` },
    { "@type": "ListItem", position: 2, name: "Are We A Good Fit?", item: PAGE_URL },
  ],
};

export default function GoodFitPage() {
  return (
    <PageComposer jsonLd={[breadcrumbJsonLd, webPageJsonLd]}>
      <SectionShell className="cw-fit-hero">
        <p className="eyebrow">Before you reach out</p>
        <h1 className="svc-hero__title">
          <span className="text-gradient">Are We A Good Fit?</span>
        </h1>
        {/* The answer itself, right under the question. These are the bare panels,
            not the periwinkle capsule the other pages render: the room asks the
            question in its H1, so the band's heading would only repeat it. FIT is
            the same copy the homepage teases, imported rather than restated. */}
        <QualPanels qualification={FIT} />
      </SectionShell>

      <SectionShell className="cw-fit-prose">
        <h2 className="svc-block__heading svc-fill">
          Every site is starting to look the same
        </h2>
        <p className="svc-block__body measure-prose">
          More websites are being made right now than at any point in history, and
          they are all converging on one layout. The same hero image, the same row
          of cards, the same photograph of a team that does not work there, the
          same sentence about passion and excellence. A lot of this is
          auto-generated by AI, which is exactly why the converging is speeding up:
          the tools learn from the average of everything already published, so the
          average is what they hand back.
        </p>
        <p className="svc-block__body measure-prose">
          I am not against the tools. I use them every day, and they changed what
          one person can finish in an afternoon. What I don&apos;t do is leave the
          taste to the tools. Something trained on the middle of the road will give
          you the middle of the road, confidently, and it will look finished enough
          that you might not know what you&apos;re leaving on the table:
          distinguished design.
        </p>
      </SectionShell>

      <SectionShell className="cw-fit-prose">
        <h2 className="svc-block__heading svc-fill">
          We are a good fit if you believe there&apos;s more to the web than social
          media.
        </h2>
        <p className="svc-block__body measure-prose">
          Many businesses rent their digital presence via social media. The
          audience is owned by the platform, not the business. The audience is
          reachable only via an algorithm that isn&apos;t published, and requires
          adherence to a system akin to that of a lottery or slot machine. A feed
          is a place you pass through, and it is built to be exactly that. What I
          build instead are{" "}
          <Link href="/about/#manifesto">digital destinations</Link>, somewhere
          worth going to on purpose, that belongs to you, that you control
          entirely: the system and the audience.
        </p>
        <p className="svc-block__body measure-prose">
          {/* Em-dash is deliberate here (Chad, 2026-07-16), overriding the
              voice profile's no-em-dash line on his own copy. Written as the
              entity so the source file stays ASCII per CLAUDE.md while the page
              still renders a real em-dash. */}
          The decision to build your own sovereign property off-social media, off
          YouTube&mdash;off any centralized platform carries weight, and financial
          requirements. The starting price for any chadworks project is {money(BASE)} but
          easily cracks {LOW} and {HIGH}. See my{" "}
          {/* Points at the live route. The href was /build-your-website-package/,
              the slug the calculator shipped under before the 2026-07-17 rename.
              That route is not in launch.ts and never will be, so LaunchLink was
              rendering this anchor as dead "coming soon" TEXT on a launched page:
              the best-placed contextual link to the calculator on the whole site
              pointed nowhere. Still LaunchLink rather than Link, so the seal keeps
              following launch.ts if the calculator is ever pulled back. */}
          <LaunchLink href="/website-design-cost-calculator/">
            website design cost calculator
          </LaunchLink>{" "}
          for more info on scoping your project.
        </p>
        <p className="svc-block__body measure-prose">
          If what you want is a placeholder to point a bio link at, my rates are
          too high and you should not pay them. If what you want is a wholly owned
          digital destination that attracts and maintains an audience or presents
          your product or service in a distinguishable manner, we are a good fit.
        </p>
      </SectionShell>

      <SectionShell className="cw-fit-prose">
        <h2 className="svc-block__heading svc-fill">
          The kind of digital destination I mean.
        </h2>
        <p className="svc-block__body measure-prose">
          The first one is this website you are reading. I built it page by page to
          convey my vision for chadworks. Have you seen any other web design
          website that looks like this? It&apos;s unlikely. If you have, please{" "}
          <LaunchLink href="/contact/">send it to me</LaunchLink>.
        </p>
        <ul className="cw-fit-list measure-prose">
          <li>
            <strong>
              <a href="https://risingcompass.net" target="_blank" rel="noopener noreferrer">
                Rising Compass
              </a>
            </strong>{" "}
            reads the lyrics of the most popular songs in the world and measures
            what they are actually saying. I designed it, built it, and run the
            whole thing.
          </li>
          <li>
            <strong>
              <a
                href="https://map.tomtheweatherwizard.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                The weather map app
              </a>
            </strong>{" "}
            lets a meteorologist sketch the snow zones straight onto a live map,
            drop the cities in, and export a finished graphic ready to post.
          </li>
          <li>
            {/* Explicit {" "} after </strong>, not a literal space: this text node
                contains an &apos; entity, and with an entity present the JSX
                whitespace pass eats the leading space right after the element.
                The two entity-free bullets above keep theirs from a plain space. */}
            <strong>
              <a href="https://chadlewine.com" target="_blank" rel="noopener noreferrer">
                The Chad Lewine website
              </a>
            </strong>{" "}
            is my own musician site, where the interaction and development goes
            deeper than any artist website in the world, because artists exist on
            platforms, they don&apos;t build their own to match their vision...{" "}
            <a
              href="https://artistempowermentsuite.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              yet
            </a>.
          </li>
        </ul>
        <p className="svc-block__body measure-prose">
          None of these started as something anybody could have bought off a shelf.
          Each one started as somebody describing a thing that did not exist yet,
          and the build worked backward from there. If you have that idea, whether
          it&apos;s for your business, your community or the globe, I want to work
          with you.
        </p>
      </SectionShell>

      <MainContactCapsule />
    </PageComposer>
  );
}
