// Price audit (pricing-hub safety net) -- the counterpart to index-audit.mjs.
//
// WHY THIS EXISTS. On 2026-07-22 the baseline moved from $3,200 to $3,250 and
// 15 files had to be edited by hand because the figure was typed into prose.
// The 2026-07-23 pass routed every chadworks price through src/lib/pricing.ts,
// which made the NEXT price change a one-line edit -- but nothing held that
// true. tsc, next build and index-audit all pass happily while a hand-typed
// "$5,000" sits in a service file. This script is what holds it true.
//
// WHAT IT CHECKS
//   1. Every price-shaped literal in src/ and public/llms.txt is either
//      hub-driven (an interpolation) or explicitly blessed in the allowlist.
//   2. Schema.org price fields (price, lowPrice, minPrice, ...) hold a hub
//      reference rather than a typed number. This is the one that is invisible
//      to a "$" grep: /rates/ shipped `price: "315"` in its JSON-LD, which is
//      exactly the figure an AI assistant lifts and quotes back.
//
// WHAT THE ALLOWLIST IS FOR. Plenty of dollar figures on this site are NOT
// chadworks prices and must stay literal: a competitor's published range, the
// $1,000-a-month retainer in the agency essay, fake numbers inside a demo
// mockup. Blessing those is correct. Blessing a chadworks price is the bug this
// script exists to prevent, so the allowlist is keyed by file AND exact literal
// AND count -- a file that gains a new figure, or one more of a figure it
// already had, fails even though the file is "known".
//
// Usage: node scripts/price-audit.mjs [--update]
//   default    exits 1 on any unblessed figure, printing file, line and value
//   --update   rewrites the allowlist from what is currently in the tree.
//              READ THE DIFF BEFORE COMMITTING IT. This flag blesses whatever
//              it finds, including a mistake you just made.
// Wired into deploy.sh beside index-audit.mjs.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { readdir } from "node:fs/promises";
import { join, relative, sep } from "node:path";

const ALLOW_FILE = join("scripts", "price-audit-allowlist.json");
const UPDATE = process.argv.includes("--update");

// A dollar figure written out: $5, $5.25, $3,250. Deliberately NOT matching
// `${...}`, because `$` followed by `{` is an interpolation -- which is the
// thing we WANT to see and the whole point of the hub.
const PRICE = /\$[0-9][0-9,]*(?:\.[0-9]{1,2})?/g;

// Schema.org money fields. A hub reference (money(HOURLY), String(BASE),
// TYPICAL_LOW) passes; a quoted or bare number does not.
const SCHEMA_PRICE = /\b(price|lowPrice|highPrice|minPrice|maxPrice)\s*:\s*("?[0-9][0-9.,]*"?)\s*[,}]/g;

// public/llms.txt is deliberately NOT scanned here. It is GENERATED by
// sync-llms-prices.mjs at prebuild, so its figures are hub-driven even though
// they sit in the file as plain text. Blessing them in this allowlist would
// hand a blanket pass to the one file that most needs watching -- $3,250,
// $315, $550 and $675 would all read as "known literals" forever. Its guard is
// the coverage assertion inside the sync script instead, which fails when a
// price sentence appears that no rule owns.
const SCAN_DIRS = ["src"];
const SCAN_FILES = [];
const EXTS = [".ts", ".tsx", ".mjs", ".md", ".txt"];

async function walk(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) await walk(full, out);
    else if (EXTS.some((e) => entry.name.endsWith(e))) out.push(full);
  }
  return out;
}

const norm = (p) => relative(process.cwd(), p).split(sep).join("/");

// --- collect ----------------------------------------------------------
const found = {};   // file -> { literal -> count }
const located = []; // { file, line, literal } for the failure report
const schemaHits = [];

const files = [...SCAN_FILES.filter(existsSync)];
for (const dir of SCAN_DIRS) if (existsSync(dir)) await walk(dir, files);

for (const file of files) {
  const key = norm(file);
  const src = readFileSync(file, "utf8");
  src.split(/\r?\n/).forEach((line, i) => {
    for (const m of line.matchAll(PRICE)) {
      (found[key] ??= {})[m[0]] = (found[key][m[0]] ?? 0) + 1;
      located.push({ file: key, line: i + 1, literal: m[0], text: line.trim() });
    }
    for (const m of line.matchAll(SCHEMA_PRICE)) {
      schemaHits.push({ file: key, line: i + 1, field: m[1], value: m[2], text: line.trim() });
    }
  });
}

// --- update mode ------------------------------------------------------
if (UPDATE) {
  const sorted = Object.fromEntries(
    Object.keys(found).sort().map((f) => [
      f,
      Object.fromEntries(Object.keys(found[f]).sort().map((l) => [l, found[f][l]])),
    ]),
  );
  writeFileSync(ALLOW_FILE, JSON.stringify(sorted, null, 2) + "\n");
  const total = Object.values(found).reduce(
    (n, lits) => n + Object.values(lits).reduce((a, b) => a + b, 0), 0);
  console.log(`price-audit: blessed ${total} literal(s) across ${Object.keys(found).length} file(s).`);
  console.log("READ THE DIFF. This just blessed whatever was in the tree.");
  process.exit(0);
}

// --- check mode -------------------------------------------------------
if (!existsSync(ALLOW_FILE)) {
  console.error(`price-audit: no allowlist at ${ALLOW_FILE}. Run with --update to seed it.`);
  process.exit(1);
}
const allow = JSON.parse(readFileSync(ALLOW_FILE, "utf8"));

const violations = [];
for (const { file, line, literal, text } of located) {
  const budget = allow[file]?.[literal] ?? 0;
  const seen = (found[file][literal] ?? 0);
  if (seen > budget) {
    violations.push({ file, line, literal, text, budget, seen });
  }
}
// One report per (file, literal), not one per occurrence.
const unique = [...new Map(violations.map((v) => [`${v.file}|${v.literal}`, v])).values()];

// A literal that DISAPPEARED is not a failure (routing one through the hub is
// the goal), but a stale allowlist entry is worth saying out loud so the file
// does not accumulate permission for figures that no longer exist.
const stale = [];
for (const [file, lits] of Object.entries(allow)) {
  for (const [literal, count] of Object.entries(lits)) {
    const now = found[file]?.[literal] ?? 0;
    if (now < count) stale.push(`${file}: ${literal} (allowed ${count}, found ${now})`);
  }
}

for (const v of unique) {
  console.error(
    `price-audit: ${v.file}:${v.line} hand-typed ${v.literal}` +
    (v.budget ? ` (${v.seen} found, ${v.budget} allowed)` : "") +
    `\n    ${v.text.slice(0, 120)}`,
  );
}
for (const s of schemaHits) {
  console.error(
    `price-audit: ${s.file}:${s.line} schema \`${s.field}\` is a typed number ${s.value}, not a hub reference` +
    `\n    ${s.text.slice(0, 120)}`,
  );
}

if (unique.length || schemaHits.length) {
  console.error(
    "\nEvery chadworks price belongs in src/lib/pricing.ts; import it and interpolate.",
    "\nIf this figure is genuinely somebody else's (a competitor's range, a client",
    "\nanecdote, a number inside a demo mockup), run `node scripts/price-audit.mjs",
    "\n--update` and check the diff blesses only what you meant.",
  );
  process.exit(1);
}

if (stale.length) {
  console.log(`price-audit: OK. ${stale.length} allowlist entr(ies) now unused, tidy when convenient:`);
  for (const s of stale) console.log(`  - ${s}`);
} else {
  console.log("price-audit OK -- no hand-typed prices outside the allowlist.");
}
