// Barrel export for the global capsule layer. Pages import capsules from here;
// composeService (lib/compose) places the canonical service order.
export { SectionShell } from "./SectionShell";
export { PageComposer, JsonLd } from "./PageComposer";
export { W, ArrowRight, CheckIcon, CtaButton } from "./shared";
export { HeroCapsule } from "./HeroCapsule";
export { KeyFactsCapsule } from "./KeyFactsCapsule";
export { ProblemCapsule, ProblemArtCapsule } from "./ProblemCapsule";
export { ApproachCapsule } from "./ApproachCapsule";
export { ProcessCapsule } from "./ProcessCapsule";
export { GemPanelCapsule } from "./GemPanelCapsule";
export { GemRevealCapsule } from "./GemRevealCapsule";
export { PathsCapsule } from "./PathsCapsule";
export { TiersCapsule } from "./TiersCapsule";
export { ProofCapsule } from "./ProofCapsule";
export { PortfolioCapsule } from "./PortfolioCapsule";
export { PortfolioShowcaseCapsule } from "./PortfolioShowcaseCapsule";
export { TestimonialsCapsule } from "./TestimonialsCapsule";
export { MadeByCapsule } from "./MadeByCapsule";
export { AboutChadCapsule } from "./AboutChadCapsule";
export { PriceCapsule } from "./PriceCapsule";
export { RatesCapsule } from "./RatesCapsule";
export { QualificationCapsule } from "./QualificationCapsule";
export { FitCapsule } from "./FitCapsule";
export { FaqCapsule } from "./FaqCapsule";
export { AssuranceCapsule } from "./AssuranceCapsule";
export { NextStepsCapsule } from "./NextStepsCapsule";
export { CtaCapsule } from "./CtaCapsule";
export { ContactCapsule } from "./ContactCapsule";
export { MainContactCapsule } from "./MainContactCapsule";
export { EraTimelineCapsule } from "./EraTimelineCapsule";
export { AnatomyCapsule } from "./AnatomyCapsule";
